name: Windows RDP via Serveo

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Set admin password
      run: net user runneradmin MySecurePassword123!

    - name: Install OpenSSH
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

    - name: Start reverse SSH tunnel to Serveo
      run: |
        ssh -o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net
