name: Windows RDP via Cloudflared

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Set admin password
      run: net user runneradmin MySecurePassword123!

    - name: Download cloudflared
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"

    - name: Start cloudflared tunnel
      run: |
        Start-Process -NoNewWindow -FilePath ".\cloudflared.exe" -ArgumentList "tunnel", "--url", "rdp://localhost:3389"
        Start-Sleep -Seconds 10

    - name: Print tunnel info
      run: |
        .\cloudflared.exe tunnel --url rdp://localhost:3389
