name: Windows RDP via Cloudflared

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360  # إبقاء الجلسة فعالة لمدة 6 ساعات

    steps:
    - name: Set admin password
      run: net user runneradmin MySecurePassword123!

    - name: Download cloudflared
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"

    - name: Start cloudflared in background
      run: |
        Start-Process -NoNewWindow -FilePath ".\cloudflared.exe" -ArgumentList "tunnel", "--url", "rdp://localhost:3389"
        Start-Sleep -Seconds 10

    - name: Keep Action alive (6 hours)
      run: |
        Write-Output "Tunnel started. Keeping session alive for 6 hours..."
        ping 127.0.0.1 -n 21601 > nul
